# @package _global_
defaults:
  - vis_mvae
  - _self_

expname: export-mvae-recon-npz
task: export-mvae-recon-npz

export:
  out_dir: ${hydra:runtime.cwd}/exports/mvae_recon_npz
  max_motions: 8
  prefix: mvae
